server:
  port: 8090
  servlet:
    context-path: /challenge

spring:
  application:
    name: challenge-meli
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bef69021497056:e8f05ca8@us-cdbr-east-03.cleardb.com/heroku_160131ab73a8533
    username: bef69021497056
    password: e8f05ca8
