version: '3.7'

services:
  db_challenge_meli:
    image: mysql:5.7.31
    container_name: db_challenge_meli
    hostname: db_challenge_meli
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'challengemelidb'
      MYSQL_USER: 'challenge'
      MYSQL_PASSWORD: 'challenge2021++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3330:3306'
    volumes:
      - ./scripts/challengedb/mysql-challenge-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-challenge-schema-v0.1.sql
    networks:
      - ntw_databases
    deploy:
      resources:
        limits:
          memory: 520M
volumes:
  data_challenge_meli:
networks:
  ntw_databases:
    external: true