SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `challengemelidb`;

CREATE SCHEMA IF NOT EXISTS `challengemelidb` DEFAULT CHARACTER SET utf8 ;

USE `challengemelidb`;

CREATE TABLE IF NOT EXISTS SERVER_ALERTS (
	ALERT_ID varchar(512) NOT NULL,
    SERVER_NAME varchar(512) NOT NULL,
	DESCRIPTION_ALERT nvarchar(512) NOT NULL,
	CREATED_AT nvarchar(20) NOT NULL,
	SERVER_TYPE varchar(50)
) ENGINE = InnoDB;

ALTER TABLE SERVER_ALERTS ADD CONSTRAINT PK_SERVER_ALERTS PRIMARY KEY (ALERT_ID);

COMMIT;
