USE `heroku_160131ab73a8533`;

DROP TABLE IF EXISTS `SERVER_ALERTS`;
DROP TABLE IF EXISTS `SERVER_INFORMATION`;

CREATE TABLE IF NOT EXISTS SERVER_INFORMATION (
	SERVER_ID varchar(50) NOT NULL,
	DESCRIPTION_SERVER varchar(100) NOT NULL,
	ACTIVE varchar(1) NOT NULL
) ENGINE = MyISAM;

ALTER TABLE SERVER_INFORMATION ADD CONSTRAINT PK_SERVER PRIMARY KEY (SERVER_ID);

COMMIT;

CREATE TABLE IF NOT EXISTS SERVER_ALERTS (
	ALERT_ID varchar(40),
    SERVER_ID varchar(50),
	DESCRIPTION_ALERT varchar(50),
	CREATED_AT DATETIME,
	SERVER_TYPE varchar(50)
) ENGINE = MyISAM;

ALTER TABLE SERVER_ALERTS ADD CONSTRAINT PK_ALERTS PRIMARY KEY (ALERT_ID);
## ALTER TABLE SERVER_ALERTS ADD CONSTRAINT FK_SERVER FOREIGN KEY (SERVER_ID) REFERENCES SERVER_INFORMATION (SERVER_ID);

ALTER TABLE SERVER_ALERTS ADD INDEX(SERVER_ID);
ALTER TABLE SERVER_ALERTS ADD INDEX(DESCRIPTION_ALERT);

ALTER TABLE SERVER_ALERTS ADD FULLTEXT (SERVER_ID, DESCRIPTION_ALERT);

COMMIT;
