USE `heroku_160131ab73a8533`;

DROP TABLE IF EXISTS `SERVER_ALERTS`;

CREATE TABLE IF NOT EXISTS SERVER_ALERTS (
	ALERT_ID varchar(30) NOT NULL,
    SERVER_NAME varchar(512) NOT NULL,
	DESCRIPTION_ALERT nvarchar(512) NOT NULL,
	CREATED_AT nvarchar(20) NOT NULL,
	SERVER_TYPE varchar(50)
) ENGINE = InnoDB;

ALTER TABLE SERVER_ALERTS ADD CONSTRAINT PK_ALERTS PRIMARY KEY (ALERT_ID);

COMMIT;